version: '3.6'


services:
    
    s_consul:
        container_name: c_consul
        image: stefanscherer/consul-windows
        ports:
            - "8500:8500"
            - "8600:8600/tcp"
            - "8600:8600/udp"
        networks:
            - localdev
  
networks:
    localdev:
        name: localdev